### ISSUE TITLE
Ugly colors in term output

### ISSUE THREAD

**Issue by akotulski** [synic/jbeans-emacs#10]
When using multiterm, blue colors are unreadable (too dark, looks very similar to background color)

I think it's because this theme doesn't set `term-color-*` variables

**Comment by synic** [comment]
Ah, I never use the terminal in emacs.  Do you have suggestions for colors?

**Comment by akotulski** [comment]
I provided example colors that make terminal readable, but I'm not sure they match this theme very well.
I didn't spend any time on background colors, maybe they should be the same as foreground.
```
;;;;; Term
       `(term-color-black                    ((,class (:foreground ,jbeans-bg :background ,jbeans-bg))))
       `(term-color-red                      ((,class (:foreground ,jbeans-red-2 :background ,jbeans-red-3))))
       `(term-color-green                    ((,class (:foreground ,jbeans-green-2 :background ,jbeans-green-3))))
       `(term-color-yellow                   ((,class (:foreground ,jbeans-yellow-3 :background ,jbeans-yellow-2))))
       `(term-color-blue                     ((,class (:foreground ,jbeans-blue-0 :background ,jbeans-blue-1))))
       `(term-color-magenta                  ((,class (:foreground ,jbeans-purple-0 :background ,jbeans-purple-3))))
       `(term-color-white                    ((,class (:foreground ,jbeans-fg :background ,jbeans-fg))))
       `(term-default-fg-color               ((,class (:inherit term-color-white))))
       `(term-default-bg-color               ((,class (:inherit term-color-black))))

```

This is how it looks like:
![screenshot from 2017-12-09 11-50-45](https://user-images.githubusercontent.com/5714083/33795000-5407b2e0-dcd7-11e7-8c00-7d41a2f23a32.png)

**Comment by synic** [comment]
I added your colors, thank you!
