### ISSUE TITLE
Spacemacs, Magit: "-" (minus) fringe indicator for deleted lines is basically invisible

### ISSUE THREAD

**Issue by xged** [synic/jbeans-emacs#8]

**Comment by synic** [comment]
Hrmm, it is not invisible for me?  Do you have a screenshot?

**Comment by xged** [comment]
`xbacklight -set 3` (set 3% brightness) :)

![screenshot from 2017-07-02 03-04-41](https://user-images.githubusercontent.com/6420591/27766279-f0e21574-5ed3-11e7-8529-d846b9b4b239.png)

**Comment by xged** [comment]
Also in `spacemacs/default-pop-shell` (`term`) folder colors!:

![screenshot from 2017-07-02 03-18-09](https://user-images.githubusercontent.com/6420591/27766355-dbb75a86-5ed5-11e7-83a1-ee2195b719d6.png)

**Comment by xged** [comment]
As we are at this :), visual selection at current line is not distinctive enough IMHO.

**Comment by synic** [comment]
Do you have suggestions for alternate colors?

**Comment by xged** [comment]
Nothing of a particular, just wanted to note you as I was having thoughts by experimenting with different themes. I do like darktooth-theme's DESIGN of Magit fringes a lot, that would solve a problem too.
